### ISSUE TITLE
Fix design, UI & UX of the app

### ISSUE THREAD

**Issue by mrkvon** [OpenHospitalityNetwork/sleepy-bike-solid#104]
Let's track possible improvements here:

- [x] #101 
- [x] show feedback messages (toast) #105 
- [ ] better messages experience #170 
- [x] #106 (only zoom)
- [x] #107 
  - [x] put titles to form inputs
  - [x] add form validation
  - [x] disallow posting location [0,0]
  - [x] safety: encourage people _not_ to select their exact localization
- [ ] improve initial loading and profile setup
- [ ] make bundle smaller - for faster load (e.g. fix lodash importing, split bundle, ...)
- [ ] feature: enable markdown for messages, profile description, etc.
- [ ] support emojis (low priority)
- [x] make clear "email verified" message when person follows email verification link https://github.com/OpenHospitalityNetwork/simple-email-notifications/commit/ce8d013e321ed1edbe6ca8699b686f423b917a33
- [x] add initial walk through the app #186
