### ISSUE TITLE
Roadmap for sleepy.bike

### ISSUE THREAD

**Issue by mariha** [OpenHospitalityNetwork/sleepy-bike-solid#44]
_This list is an ongoing Work In Progress, by intention._

# Roadmap for sleepy.bike

- [ ] Grow and maintain production community at https://sleepy.bike
    - maintain server infrastructure (app(s), sleepy bike community pod, index for geosearch, email notifications service, ...)
    - maintain social media site(s)
    - spread the information about the community

- [x] #70
   to make search of accommodations scalable

- [x] #71
   Email notifications service will receive notifications about new items in members' inbox, and send email when appropriate

- [ ] #104
  That's a long way to go...

- [x] Internationalization (i18n) - translate the website and make it available in multiple languages
  People should be able to use the website in different languages, and also provide their information in multiple languages

- [x] Extract library for querying data, and make it more efficient
   so other people can use it

- [ ] Make the community independent of a single list of members (https://community.sleepy.bike)
   To remove the single point of failure and control, which central list of members is

- [ ] Build app for community management
   A less-than-minimal version [already exists](https://github.com/OpenHospitalityNetwork/solid-community-manager), but it's buggy and many functionalities are missing

- [ ] Support ESS (Enterprise Solid Server) and Trinpod and other Solid pods
   - support ACP access control? (Access Control Policies is alternative way of access control to ACL (Access Control List) that is used by ESS)

- [ ] Make option to have invite-only community
   Some communities want to grow more slowly and be more exclusive

- [ ] Make it easy to deploy the app for different communities
   - customization of looks and functionality
   - good documentation

- [ ] ...

---

- [ ] Long term: make other community apps that members can use
   * The goals of these apps are:
      - meaningful connections
      - reality
      - sustainability

   * Some ideas include:
      - collaboration
      - founding intentional communities
      - unschooling
      - sharing spaces and resources
      - ....

**Comment by mrkvon** [comment]
Closing in favour of https://github.com/orgs/solidcouch/projects/2.
